@startuml
hide footbox

participant  "main : MainLaby" as main
participant  "moteur : MoteurJeu" as m
participant  "jeu : LabyJeu" as LJ
participant  "laby : Labyrinthe" as laby
participant "piege : CasePiege" as pc

main -> m : launch(jeu, dessin)
activate m

m -> LJ: update()
activate LJ

LJ -> laby: deplacerPerso("Haut", perso)
activate laby
laby -> pc : declencher(perso)
activate pc
pc -> pc : setActiver(true)
pc -> perso : perdrePv(25)
activate perso
pc <-- perso
deactivate perso
laby <-- pc
deactivate pc
 

LJ <-- laby 
deactivate laby
m <--LJ
deactivate LJ

main <-- m
deactivate m


 
@enduml
